spring:
  config:
    import: credentials.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  thymeleaf:
    cache: false # true when production
log4j:
  logger:
    org:
      mybatis:
        example: DEBUG
logging:
  config: classpath:logback.xml
mybatis-plus:
  mapper-locations: classpath:net/fileme/domain/mapper/*.xml
  configuration:
# 將MyBatis sql command輸出至console
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 將MyBatis sql command輸出至log
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl