spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/4test
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
log4j:
  logger:
    org:
      mybatis:
        example: DEBUG
logging:
  config: classpath:logback.xml
mybatis-plus:
  mapper-locations: classpath:net/fileme/domain/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 預設檔案上傳路徑
file:
  upload:
    dir: /Users/yvon/ideaUploads
# 預設垃圾桶目錄id
  trash:
    folderId: 999
# 預設根目錄id
  root:
    folderId: 0