spring:
  config:
    import: "credentials.properties"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
log4j:
  logger:
    org:
      mybatis:
        example: DEBUG
logging:
  config: classpath:logback.xml
mybatis-plus:
  mapper-locations: classpath:net/fileme/domain/mapper/*.xml
  configuration:
# 將MyBatis sql command輸出至console
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 將MyBatis sql command輸出至log
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# 預設檔案上傳路徑
#file:
#  upload:
#    dir: /Users/yvon/ideaUploads
# 預設垃圾桶目錄id
#  trash:
#    folderId: 999
# 預設根目錄id
#  root:
#    folderId: 0
# JWT
jwt:
  exp: 60 * 60 * 1000L # 毫秒
  key: fileme
  issuer: hahaha